### ISSUE TITLE
自动刷新token的问题

### ISSUE THREAD

**Issue by junsonw** [go-pay/wechat-sdk#5]
我们网站使用了这个自动刷新token发现协程会无缘无故增加 最后发现是
```
if s.autoManageToken {
// 自动刷新 AccessToken
go s.goAutoRefreshAccessToken()
}
```
```
func (s *SDK) goAutoRefreshAccessToken() {
	defer func() {
		if r := recover(); r != nil {
			buf := make([]byte, 64<<10)
			buf = buf[:runtime.Stack(buf, false)]
			xlog.Errorf("open_goAutoRefreshAccessToken: panic recovered: %s\n%s", r, buf)
		}
	}()
	for {
		// every one hour, request new access token, default 10s
		time.Sleep(s.RefreshInternal / 2)
		err := s.refreshAccessToken()
		if err != nil {
			xlog.Errorf("get access token error, after 10s retry: %+v", err)
			continue
		}
	}
}
```
这里走了一个死循环 如果有十万人登录微信 就会有十万个协程一直不退出等着刷token 这个非常的可怕

**Comment by iGoogle-ink** [comment]
是不是使用方式不对呢？client 只要初始化一次就行了，token 应该是应用级别的，不是用户级别的吧
为什么每个人登录，都会自动刷新token呢？

**Comment by iGoogle-ink** [comment]
> 我们网站使用了这个自动刷新token发现协程会无缘无故增加 最后发现是
> 
> ```
> if s.autoManageToken {
> // 自动刷新 AccessToken
> go s.goAutoRefreshAccessToken()
> }
> ```
> 
> ```
> func (s *SDK) goAutoRefreshAccessToken() {
> 	defer func() {
> 		if r := recover(); r != nil {
> 			buf := make([]byte, 64<<10)
> 			buf = buf[:runtime.Stack(buf, false)]
> 			xlog.Errorf("open_goAutoRefreshAccessToken: panic recovered: %s\n%s", r, buf)
> 		}
> 	}()
> 	for {
> 		// every one hour, request new access token, default 10s
> 		time.Sleep(s.RefreshInternal / 2)
> 		err := s.refreshAccessToken()
> 		if err != nil {
> 			xlog.Errorf("get access token error, after 10s retry: %+v", err)
> 			continue
> 		}
> 	}
> }
> ```
> 
> 这里走了一个死循环 如果有十万人登录微信 就会有十万个协程一直不退出等着刷token 这个非常的可怕

感谢提出问题，code2session 这块，确实跟用户登录有关系

**Comment by iGoogle-ink** [comment]
之前忽略了，开放平台的 AccessToken 都是用户级别的， 并不是应用级别的，之前看看小程序的，想成一样的场景了，感谢提出来，

**Comment by iGoogle-ink** [comment]
v1.1.3 问题已修复，希望帮忙参考参考可用性
